version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15

    working_directory: /go/src/github.com/gomatic/funcmap
    steps:
      - checkout
      - run: make
